spring:
  application:
    name: gateway

server:
  port: 8080

security:
  jwt:
    issuer: http://localhost:8081
    audience: roleradar-api
    jwk-set-uri: http://localhost:8081/.well-known/jwks.json
  cookies:
    access-token-name: access_token
    refresh-token-name: refresh_token
    secure: false # true in prod
    same-site: Lax # Strict in prod

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /aggregate/auth-service/v3/api-docs
