spring:
  application:
    name: gateway

server:
  port: 8080

security:
  jwt:
    issuer: http://localhost:8081
    audience: roleradar-api
    jwk-set-uri: http://localhost:8081/.well-known/jwks.json
    access-token-cookie-name: access_token

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /aggregate/auth-service/v3/api-docs
