spring:
  application:
    name: ingestion-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8083

roleradar:
  ingestion:
    scheduling:
      enabled: true
      remotive-cron: "0 0 */8 * * *"
      arbeitnow-cron: "0 0 */2 * * *"
      adzuna-cron: "0 0 */2 * * *"

    remotive:
      base-url: https://remotive.com
      max-jobs-per-run: 10 # temporary var for testing only

    arbeitnow:
      base-url: https://www.arbeitnow.com
      max-jobs-per-run: 50 # temporary var for testing only
      max-pages-per-run: 3 # temporary var for testing only

    adzuna:
      base-url: https://api.adzuna.com/v1/api
      app-id: ${ADZUNA_APP_ID}
      app-key: ${ADZUNA_APP_KEY}
      countries: pl,de,nl,fr,es,it
      search-terms: java developer,backend developer,software engineer
      max-jobs-per-run: 100 # temporary var for testing only
      results-per-page: 50 # temporary var for testing only
      max-pages-per-run: 3 # temporary var for testing only

    topics:
      vacancy-upserted: vacancy-upserted
